[tool.poetry]
name = "pyevm"
version = "0.1.0"
description = ""
authors = ["kidneyweakx <kidneyweaks@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pysha3 = "^1.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
